theme: jekyll-theme-minimal
title: Fastac Adhesive Label
description: PT. Sumber Inti Aneka Sempana, Indonesia Adhesive label Manufacturer
logo: /assets/img/logo640x400.png

github:
  is_project_page: false